language: java
jdk:
- oraclejdk8
sudo: required
services:
  - docker
cache:
  directories:
  - "$HOME/.gradle"
install: true
script: "./gradlew build"
deploy:
  provider: script
  script: ./docker-push.sh
  on:
    branch: master
env:
  global:
  - secure: J5fC36uw+PS14l/MPfB4CYQpsy8Ai4U5riBddl/nSrE3nbYGnIeZ9iEsORFMI7zepfz0A6nRgBIyolcuRmLHvegVba6cz+ZKRPdrC4gCSrZ9KOtDhr/gC9IsRVs266c8yZfA0TfYqi6jYsBbbYCv4ZeU9jccJA5NvT/ClTk5GCB2k/apzAc9kXjzCUsOpjBi1ufSjzeB/hE+crkZLCRr61dJFduPjAkJlG0IC3X1j2oiOL/o7aCdufIDJYijb206jia6SUpA833hSdBh7vfLOahbsWJa2OSFZa24j5tjYVAnKEuqfk/fwKecUM91cWIfXGSDb22bZRqITunKgzsIjKnVA4PqLioICl7I9Y7K984nxM1d2H3llIr9CDtlawLzQXOA5D0obX/lNECFlwcp6PxUjz7lsO7IhcI1/3s5L2hR9tskGG0IUgM/iPvguKEpMV8qRbI1klcOmuxwx5gQz/ePnRL+do6c29oVs8ek0pq3ArCrisJq+GupAb22h6FVbAATbQebTPiwVPKHKhyrDi0oZIsFv/UsBVgwQNSCH8tdFyjTW2JIEMTrGKN99EToKKRyYlEc1k08NmLQk9VQ86O82vtfpoCg+FcSG/J/i9YIgT7Qy2Pb6op6TSzZsTyCvf5RHlS6iB6sNqYSg9EQjJZIImPY+CMQ4bzvxu5xakk=
  - secure: fXrtYEk5GW11fje8107MDB66GmuTk8PrDXGqZOKKnxivEx6ZJXT9mgJqMh6ucy67TxA+K3M/o8Ddl8CCx+1cE7/tUFfRzhKI1eO/UeEcN7XfOumPOjz38vEz3cK9HwLJSlxUlOoms+SErws4S3IdHypZcT23hzOHRy7t+E1C3+QG4jsvkxRj4YUup0X9gYZ4c89w4IE8KBZhrRYwbxpBYxZRF1Qw8a727v4/oZPbK2ljeyp+ImyqskZqJADiORkuyeqEUPrhoJXZAtr37KpiiGUfMDrP1X1ZGgT7vCB7nzCSfqJIi7bvPSDysBdCS/Gbaikh3MEUdLQbWEi4E7J+Vj+3GSGmRPXinL+NjnRjHaoXgINqOCcbjZamWahpAnXvKQltIIlf0tIJP7kfSTvHfpTy+5W1SOvgkxVpTnHeQ7PKHutQQO3y1c8C0Z2OK5kIohSHmVxtDKfRR7Mge+KbULdPg7ZBfA1GrWN8wO9V5nmfmw+rgk8ucYUVdqpYGxqMGkRwsKtjyHXGudFhr2hGPwepIyr8cXujQAFc1IRNeqtZpiY9MLNfX+DEUqImEYpgkq/RnR038xkUlhaupeJxdELNAd01wTyzo+uGK1mz0Gs7731Sw4GMIMuWHLkeN6JTMA4a8003HZE9NMrz5R8wr+FjYWXqcKelriRaXvGdCJI=
  - secure: uIVOG3II7aBsHtreDSo+CfyF4RE+M47WWUKk47lbrOYAamGKobBTCfEBaubgVkCW+IRj0AkahMgIKXs/atCVLn9tEKsa66xIBsJflTe5TYBxWYJS0NAMA0IhgzQQgdUV8lozko6OnVOJ7wCOmpCOfpKRCnOszazFfXgUb8SqtzYvxzjdRhkoI3BvsIDm1U2E8hJnmJLLKiZVouERzj5Q61cJUGX36faapFgYLzwiW4iEYlyMnW/74/JwuEKDgIbfrmA+x5dPDVGh9jsnbcewTWq910KsD0qWmQJI5tDlaA6SnE8Ye0pk1DCVoz1j6a/KT+VDlrpjSiaU30BivB0jTQqFxAVIKuehM1DYxJ3WZjtlvcZOpH58y3gV3IGoykSM+PUzgtTED8IO9twvB9uMb/YjFhx1SX++SjUVNX93AdPOE61i5rpnTF1jkGoBsX0WWRgugYIrEh6SdcoJ+Jc7CzuYa51IQTIBGJcYNptKgRrzkbu4INIPBcsPizw3Wqnerhpl9ZeSEDmSm5JPT5Tq8XxRYe7Krm8E47jdHraQfGVif9pvcguGF03xCGeyDKONAsShPkCWLlB6kMEtcb3dCXSwXSj4GY5iwVgjn/BXkzDREXN9lYbTdTy1X1VxPEgr1og1Ao27YtyMomkQgJ3uNwBQmI9enwMmju7hNGB6Igc=

